import { RestaurantConfig, Product, FAQItem } from "./types";

export const RESTAURANT_CONFIG: RestaurantConfig = {
  name: "XIAN SUSHI",
  city: "Foggia",
  address: "Via Manfredonia 37, 71121 Foggia FG",
  phone: "+393778297346",
  phoneDisplay: "377 8297346",
  whatsapp: "+393778297346",
  whatsappDisplay: "377 8297346",
  email: "info@xiansushifoggia.it",
  coordinates: {
    lat: 41.4721,
    lng: 15.5684,
  },
  // High-quality maps embed centered in Foggia (Via Manfredonia 37)
  mapsEmbedUrl: "https://maps.google.com/maps?q=Via%20Manfredonia%2037,%20Foggia&t=&z=15&ie=UTF8&iwloc=&output=embed",
  mapsExternalUrl: "https://maps.google.com/?q=Xian+Sushi+Foggia+Via+Manfredonia+37+Foggia",
  hours: {
    closedDay: "Sempre Aperto",
    openDays: "Tutti i giorni",
    lunchTime: "12:30 - 15:30",
    dinnerTime: "19:30 - 00:00",
    daily: [
      { day: "Lunedì", shifts: ["12:30 - 15:30", "19:30 - 00:00"] },
      { day: "Martedì", shifts: ["19:30 - 00:00"] },
      { day: "Mercoledì", shifts: ["12:30 - 14:30", "19:30 - 23:30"] },
      { day: "Giovedì", shifts: ["12:30 - 14:30", "19:30 - 00:00"] },
      { day: "Venerdì", shifts: ["12:30 - 15:00", "19:30 - 00:00"] },
      { day: "Sabato", shifts: ["12:30 - 15:30", "19:30 - 00:30"] },
      { day: "Domenica", shifts: ["12:30 - 15:30", "19:30 - 00:00"] },
    ],
  },
  cuisine: "Sushi, Cucina giapponese, Asian Fusion",
  priceRange: "€€",
  areaServed: [
    "Foggia",
    "San Severo",
    "Lucera",
    "Manfredonia",
    "Cerignola",
    "Orta Nova",
    "San Giovanni Rotondo",
    "Troia",
  ],
  prices: [
    {
      id: "pranzo-settimana",
      title: "Pranzo in Settimana",
      price: 16.90,
      description: "Formula pranzo dal martedì al venerdì.",
      note: "Bevande, dolci e coperto esclusi.",
      image: "antipasto.png",
    },
    {
      id: "cena-settimana",
      title: "Cena in Settimana",
      price: 26.90,
      description: "Formula cena dal martedì al venerdì.",
      note: "Bevande, dolci e coperto esclusi.",
      image: "sashimi.png",
    },
    {
      id: "pranzo-weekend",
      title: "Pranzo Weekend & Festivi",
      price: 18.90,
      description: "Formula pranzo per sabato, domenica e giorni festivi.",
      note: "Bevande, dolci e coperto esclusi.",
      image: "temaki.png",
    },
    {
      id: "cena-weekend",
      title: "Cena Weekend & Festivi",
      price: 28.90,
      description: "Formula cena per sabato, domenica e giorni festivi.",
      note: "Bevande, dolci e coperto esclusi.",
      image: "nigiri.png",
    },
  ],
  instagramUrl: "https://www.instagram.com/xiansushi_foggia/",
  facebookUrl: "https://www.facebook.com/sushixian888/",
};

export const CATEGORIES = [
  "Antipasti",
  "Primi Piatti",
  "Secondi Piatti",
  "Sashimi & Sushi Misto",
  "Nigiri",
  "Hosomaki",
  "Uramaki",
  "Futomaki",
  "Gunkan",
  "Temaki",
  "Onigiri",
  "Dolci",
  "Bevande",
  "Birre"
];

export const CATEGORY_IMAGES: Record<string, string> = {
  "Antipasti": "antipasto.png",
  "Primi Piatti": "primo.png",
  "Secondi Piatti": "secondo.png",
  "Sashimi & Sushi Misto": "sashimi.png",
  "Nigiri": "nigiri.png",
  "Hosomaki": "hosomaki.png",
  "Uramaki": "uramaki.png",
  "Futomaki": "futomaki.png",
  "Gunkan": "gunkan.png",
  "Temaki": "temaki.png",
  "Onigiri": "onigiri.png",
  "Dolci": "dolce.png",
  "Bevande": "bevanda.png",
  "Birre": "birra.png"
};

export const PRODUCTS: Product[] = [
  // Antipasti (sorted alphabetically)
  { id: "ant-5", name: "Edamame", price: 3.50, category: "Antipasti" },
  { id: "ant-14", name: "Goma wakame", price: 4.00, category: "Antipasti" },
  { id: "ant-11", name: "Gua bao", description: "Pulled di maiale, teriyaki", price: 3.00, category: "Antipasti" },
  { id: "ant-9", name: "Insalata con gamberi", price: 4.00, category: "Antipasti" },
  { id: "ant-16", name: "Insalata di mango", description: "Salmone, salsa mango", price: 6.00, category: "Antipasti" },
  { id: "ant-15", name: "Insalata mista", price: 3.00, category: "Antipasti" },
  { id: "ant-2", name: "Involtini primavera", description: "Con verdure", price: 2.50, category: "Antipasti" },
  { id: "ant-10", name: "Involtini salmone", price: 3.50, category: "Antipasti" },
  { id: "ant-8", name: "Involtini vietnamiti", price: 3.00, category: "Antipasti" },
  { id: "ant-7", name: "Nuvole di drago", price: 2.50, category: "Antipasti" },
  { id: "ant-12", name: "Pane cinese", description: "Al vapore", price: 3.00, category: "Antipasti" },
  { id: "ant-13", name: "Pane fritto", price: 3.00, category: "Antipasti" },
  { id: "ant-1", name: "Ravioli alla griglia", price: 3.50, category: "Antipasti" },
  { id: "ant-3", name: "Ravioli di carne", price: 3.50, category: "Antipasti" },
  { id: "ant-6", name: "Shao mai", price: 4.00, category: "Antipasti" },
  { id: "ant-4", name: "Takoyaki", price: 4.00, category: "Antipasti" },
  { id: "ant-19", name: "Zuppa agropiccante", price: 3.00, category: "Antipasti" },
  { id: "ant-18", name: "Zuppa con frutti di mare", price: 3.00, category: "Antipasti" },
  { id: "ant-17", name: "Zuppa di miso", description: "Zuppa di soia, tofu, alga", price: 3.00, category: "Antipasti" },

  // Primi Piatti (sorted alphabetically)
  { id: "pri-5", name: "Gnocchi di riso saltati", description: "Uova, verdure", price: 5.00, category: "Primi Piatti" },
  { id: "pri-14", name: "Noodles saltati con carne", description: "Uovo, verdure, salsa di soia, teriyaki", price: 6.50, category: "Primi Piatti" },
  { id: "pri-8", name: "Ramen", description: "Spaghetti, brodo di carne, uovo sodo, verdure, narutomaki", price: 6.00, category: "Primi Piatti" },
  { id: "pri-11", name: "Riso al curry", description: "Riso, uovo, pollo, curry", price: 4.00, category: "Primi Piatti" },
  { id: "pri-6", name: "Riso alla cantonese", description: "Riso, uovo prosciutto cotto, piselli", price: 4.00, category: "Primi Piatti" },
  { id: "pri-10", name: "Riso bianco", price: 1.50, category: "Primi Piatti" },
  { id: "pri-12", name: "Riso con verdure", description: "Riso, uovo, verdure, salsa agropiccante", price: 4.50, category: "Primi Piatti" },
  { id: "pri-3", name: "Riso venere saltato", description: "Uovo, gamberi, piselli", price: 5.50, category: "Primi Piatti" },
  { id: "pri-1", name: "Spaghetti di riso con gamberi", description: "Uovo, verdure, gamberi", price: 5.00, category: "Primi Piatti", popular: true },
  { id: "pri-9", name: "Spaghetti di soia con frutti di mare", description: "Verdure, frutti di mare", price: 5.00, category: "Primi Piatti" },
  { id: "pri-2", name: "Spaghetti di soia con verdure", price: 4.00, category: "Primi Piatti" },
  { id: "pri-7", name: "Spaghetti saltati con carne", description: "Uovo, verdure, maiale, agro piccante", price: 5.00, category: "Primi Piatti" },
  { id: "pri-4", name: "Udon con frutti di mare", description: "Spaghetti, uovo, verdure, frutti di mare", price: 8.00, category: "Primi Piatti" },
  { id: "pri-13", name: "Yaki soba", description: "Uovo, verdure, salsa di soia", price: 6.00, category: "Primi Piatti" },

  // Secondi Piatti (sorted alphabetically)
  { id: "sec-27", name: "Anatra alla pechinese", description: "Teriyaki", price: 7.00, category: "Secondi Piatti" },
  { id: "sec-28", name: "Anatra all’arancia", price: 7.00, category: "Secondi Piatti" },
  { id: "sec-5", name: "Calamari fritti", price: 5.50, category: "Secondi Piatti", popular: true },
  { id: "sec-22", name: "Cotoletta di maiale", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-11", name: "Frittura mista di verdure", price: 4.00, category: "Secondi Piatti" },
  { id: "sec-23", name: "Frutti di mare saltati", description: "Verdure, olio piccante, sals soia", price: 7.00, category: "Secondi Piatti" },
  { id: "sec-25", name: "Gamberi al limone", price: 7.00, category: "Secondi Piatti" },
  { id: "sec-10", name: "Gamberi fritti", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-29", name: "Gamberi sale e pepe", description: "Peperoni", price: 7.00, category: "Secondi Piatti" },
  { id: "sec-13", name: "Gamberoni alla griglia", description: "Teriyaki", price: 10.00, category: "Secondi Piatti" },
  { id: "sec-26", name: "Maiale agrodolce", description: "Ananas, peperoni", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-21", name: "Maiale piccante", description: "Peperoni, cipolla, olio piccante, sals soia", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-2", name: "Maiale, funghi e bambù", description: "Salsa di soia", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-4", name: "Patatine fritte", price: 3.00, category: "Secondi Piatti" },
  { id: "sec-8", name: "Pollo agrodolce", description: "Ananas, peperoni", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-19", name: "Pollo al curry", description: "Con verdure, cipolla", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-7", name: "Pollo al limone", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-17", name: "Pollo alla griglia", description: "Teriyaki", price: 6.00, category: "Secondi Piatti" },
  { id: "sec-1", name: "Pollo con mandorle", description: "Salsa di soia", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-9", name: "Pollo fritto", price: 4.50, category: "Secondi Piatti" },
  { id: "sec-20", name: "Pollo piccante", description: "Carole, peperoni, olio piccante", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-6", name: "Pollo, funghi e bambù", description: "Salsa di soia", price: 5.50, category: "Secondi Piatti" },
  { id: "sec-14", name: "Salmone alla griglia", description: "Teriyaki", price: 10.00, category: "Secondi Piatti" },
  { id: "sec-12", name: "Spiedini di gamberi alla griglia", description: "Teriyaki", price: 7.00, category: "Secondi Piatti" },
  { id: "sec-16", name: "Spiedini di pollo alla griglia", description: "Cipollotto, teriyaki", price: 6.00, category: "Secondi Piatti" },
  { id: "sec-15", name: "Spiedini di seppie alla griglia", description: "Cipollotto, teriyaki", price: 6.00, category: "Secondi Piatti" },
  { id: "sec-3", name: "Tempura di gamberi", price: 7.50, category: "Secondi Piatti" },
  { id: "sec-24", name: "Verdure miste di stagione saltate", price: 4.00, category: "Secondi Piatti" },
  { id: "sec-18", name: "Vitello piccante", description: "Carole, peperoni, olio piccante", price: 7.00, category: "Secondi Piatti" },

  // Sashimi & Sushi Misto (sorted alphabetically)
  { id: "sas-2", name: "Barca piccola", description: "Sushi misto 28 pezzi", price: 28.00, category: "Sashimi & Sushi Misto", popular: true },
  { id: "sas-5", name: "Carpaccio misto", price: 8.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-6", name: "Carpaccio salmone", price: 8.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-8", name: "Chirashi misto", description: "Riso, pesce misto, teriyaki", price: 10.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-11", name: "Flower beef", description: "Manzo scottato, rucola, teriyaki", price: 3.50, category: "Sashimi & Sushi Misto" },
  { id: "sas-10", name: "Flower salmon", description: "Salmone scottato, rucola, teriyaki", price: 3.50, category: "Sashimi & Sushi Misto" },
  { id: "sas-1", name: "Sashimi misto", price: 10.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-3", name: "Sashimi salmone", price: 10.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-7", name: "Shake tataki", description: "Salmone scottato, limone, teriyaki", price: 8.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-4", name: "Tartare di salmone", description: "Salmone, avocado, ponzu, kataifi", price: 7.00, category: "Sashimi & Sushi Misto" },
  { id: "sas-9", name: "Tonno tataki", description: "Tonno scottato, teriyaki", price: 9.00, category: "Sashimi & Sushi Misto" },

  // Nigiri (sorted alphabetically)
  { id: "nig-8", name: "Anguilla", price: 4.00, category: "Nigiri" },
  { id: "nig-4", name: "Beef", price: 3.50, category: "Nigiri" },
  { id: "nig-11", name: "Black salmon", price: 3.00, category: "Nigiri" },
  { id: "nig-6", name: "Branzino", price: 3.00, category: "Nigiri" },
  { id: "nig-10", name: "Branzino scottato", price: 3.50, category: "Nigiri" },
  { id: "nig-5", name: "Gambero cotto", price: 3.00, category: "Nigiri" },
  { id: "nig-7", name: "Polpa di granchio", price: 3.00, category: "Nigiri" },
  { id: "nig-9", name: "Polpo", price: 3.00, category: "Nigiri" },
  { id: "nig-1", name: "Salmone", price: 3.00, category: "Nigiri" },
  { id: "nig-2", name: "Salmone scottato", price: 3.50, category: "Nigiri" },
  { id: "nig-3", name: "Tonno", price: 3.50, category: "Nigiri" },

  // Hosomaki (sorted alphabetically)
  { id: "hos-11", name: "Avocado", price: 4.00, category: "Hosomaki" },
  { id: "hos-9", name: "California", description: "Granchio, cetrioli", price: 3.00, category: "Hosomaki" },
  { id: "hos-10", name: "Ebi", description: "Gamberi", price: 3.50, category: "Hosomaki" },
  { id: "hos-2", name: "Ebiten", description: "Tempura di gamberi", price: 3.50, category: "Hosomaki" },
  { id: "hos-12", name: "Granchio fritto", price: 3.50, category: "Hosomaki" },
  { id: "hos-6", name: "Kano roll", price: 3.00, category: "Hosomaki" },
  { id: "hos-8", name: "Kappa", description: "Cetrioli", price: 3.00, category: "Hosomaki" },
  { id: "hos-3", name: "Shake", description: "Salmone", price: 3.50, category: "Hosomaki" },
  { id: "hos-1", name: "Spicy salmon", price: 3.50, category: "Hosomaki" },
  { id: "hos-4", name: "Spicy tuna", price: 4.50, category: "Hosomaki" },
  { id: "hos-7", name: "Takuan maki", description: "Rapa gialla", price: 3.00, category: "Hosomaki" },
  { id: "hos-5", name: "Tekka", description: "Tonno", price: 3.50, category: "Hosomaki" },

  // Uramaki (sorted alphabetically)
  { id: "ura-25", name: "Beef", description: "Manzo scottato, avocado, cetrioli, tartufo, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-8", name: "Black ebi", description: "Riso venere, gamberi fritti, rucola, philadelphia, teriyaki", price: 9.00, category: "Uramaki" },
  { id: "ura-2", name: "Black shake", description: "Riso venere, salmone, avocado, philadelphia, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-17", name: "Black shake", description: "Salmone, tobiko, avocado, nachos, spicy, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-1", name: "California", description: "Granchio, cetrioli, avocado, maionese, cipolla fritta", price: 8.00, category: "Uramaki", popular: true },
  { id: "ura-19", name: "Chicken roll", description: "Pollo, verdure, salsa dello chef contiene aglio", price: 9.00, category: "Uramaki" },
  { id: "ura-5", name: "Ebi tempura", description: "Gamberi fritti, avocado, kataifi, teriyaki", price: 9.00, category: "Uramaki" },
  { id: "ura-26", name: "Hilo", description: "Salmone, avocado, gambero rosso, ponzu", price: 6.00, category: "Uramaki" },
  { id: "ura-15", name: "Hot Roll", description: "Salmone, zucchine, kataifi, salsa thai, salsa piccante, maionese, rucola", price: 10.00, category: "Uramaki" },
  { id: "ura-20", name: "Maguro", description: "Tonno, avocado", price: 9.00, category: "Uramaki" },
  { id: "ura-6", name: "Maki fritto", description: "Salmone, philadelphia, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-14", name: "Maki mango", description: "Salmone, philadelphia, mango", price: 10.00, category: "Uramaki" },
  { id: "ura-4", name: "Maki philadelphia", description: "Salmone, avocado, philadelphia, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-10", name: "Mango ebiten", description: "Gamberi fritti, philadelphia, mango, teriyaki, salsa mango", price: 10.00, category: "Uramaki" },
  { id: "ura-3", name: "Miura maki", description: "Salmone cotto, philadelphia, teriyaki", price: 9.00, category: "Uramaki" },
  { id: "ura-21", name: "Miura tuna", description: "Tonno cotto, philadelphia, teriyaki", price: 9.00, category: "Uramaki" },
  { id: "ura-27", name: "Old california", description: "Base california, tobiko", price: 9.00, category: "Uramaki" },
  { id: "ura-11", name: "Philadelphia ebi", description: "Gambero cotto, avocado, philadelphia, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-16", name: "Rainbow", description: "Base california, pesce misto, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-18", name: "Shake", description: "Salmone, avocado", price: 9.00, category: "Uramaki" },
  { id: "ura-13", name: "Shake fritto", description: "Salmone, teriyaki", price: 9.00, category: "Uramaki" },
  { id: "ura-12", name: "Spicy salmon", description: "Salmone, avocado, salsa piccante", price: 9.00, category: "Uramaki" },
  { id: "ura-7", name: "Spicy tuna", description: "Tonno, avocado, salsa piccante", price: 9.00, category: "Uramaki" },
  { id: "ura-23", name: "Summer roll", description: "Base california, wakame, tobiko", price: 8.50, category: "Uramaki" },
  { id: "ura-9", name: "Tiger roll", description: "Gamberi fritti, salmone, teriyaki", price: 10.00, category: "Uramaki" },
  { id: "ura-22", name: "Vegetariano", description: "Insalata, cetrioli, avocado", price: 7.00, category: "Uramaki" },
  { id: "ura-24", name: "Vegetariano 2", description: "Rapa gialla, avocado, cetrioli, kataifi", price: 8.00, category: "Uramaki" },
  { id: "ura-28", name: "Vegetariano 3", description: "Carote fritte, avocado", price: 7.00, category: "Uramaki" },

  // Futomaki (sorted alphabetically)
  { id: "fut-2", name: "California", description: "Granchio, cetrioli, avocado, maionese", price: 5.00, category: "Futomaki" },
  { id: "fut-1", name: "Ebiten", description: "Gamberi fritti, cetrioli, maionese, teriyaki", price: 6.00, category: "Futomaki" },
  { id: "fut-4", name: "Maguro", description: "Tonno, avocado", price: 5.00, category: "Futomaki" },
  { id: "fut-3", name: "Shake", description: "Salmone, avocado", price: 5.00, category: "Futomaki" },

  // Gunkan (sorted alphabetically)
  { id: "gun-6", name: "Chuka wakame", price: 4.00, category: "Gunkan" },
  { id: "gun-4", name: "Cucuberi", description: "Tartare di salmone, cetrioli, teriyaki", price: 4.00, category: "Gunkan" },
  { id: "gun-9", name: "Ikura", description: "Uova di salmone", price: 5.00, category: "Gunkan" },
  { id: "gun-1", name: "Joe", description: "Salmone, philadelphia, teriyaki", price: 4.50, category: "Gunkan" },
  { id: "gun-2", name: "Joe scottato", description: "Salmone scottato, philadelphia, mandorle, teriyaki", price: 4.50, category: "Gunkan" },
  { id: "gun-10", name: "Kani", description: "Granchio, maio, maionese, teriyaki", price: 4.50, category: "Gunkan" },
  { id: "gun-5", name: "Salmone out", description: "Granchio, cetrioli, avocado, maionese", price: 4.00, category: "Gunkan" },
  { id: "gun-3", name: "Spicy salmon", description: "Salmone, spicy, teriyaki", price: 4.50, category: "Gunkan" },
  { id: "gun-7", name: "Spicy tuna", description: "Tonno, spicy, teriyaki", price: 5.00, category: "Gunkan" },
  { id: "gun-8", name: "Tobiko", description: "Uova di pesce volante", price: 4.50, category: "Gunkan" },

  // Temaki (sorted alphabetically)
  { id: "tem-6", name: "California", description: "Granchio, avocado, cetrioli, maionese", price: 3.50, category: "Temaki" },
  { id: "tem-8", name: "Ebi", description: "Gamberi cotti, avocado", price: 4.00, category: "Temaki" },
  { id: "tem-4", name: "Ebiten", description: "Gamberi fritti, cetrioli, maio, teriyaki", price: 4.00, category: "Temaki" },
  { id: "tem-7", name: "Maguro", description: "Tonno, avocado", price: 4.00, category: "Temaki" },
  { id: "tem-1", name: "Miura", description: "Salmone cotto, philadelphia", price: 4.00, category: "Temaki" },
  { id: "tem-5", name: "Shake", description: "Salmone, avocado", price: 3.50, category: "Temaki" },
  { id: "tem-2", name: "Spicy salmon", description: "Salmone, avocado, salsa piccante", price: 3.50, category: "Temaki" },
  { id: "tem-3", name: "Spicy tuna", description: "Tonno, avocado, salsa piccante", price: 4.50, category: "Temaki" },
  { id: "tem-9", name: "Vegetariano", description: "Avocado, cetrioli", price: 3.00, category: "Temaki" },

  // Onigiri (sorted alphabetically)
  { id: "oni-3", name: "Kani", description: "Surimi, maionese", price: 3.00, category: "Onigiri" },
  { id: "oni-2", name: "Maguro", description: "Tonno, avocado", price: 3.00, category: "Onigiri" },
  { id: "oni-1", name: "Miura", description: "Salmone cotto, philadelphia", price: 3.00, category: "Onigiri" },
  { id: "oni-5", name: "Miura tuna", description: "Tonno cotto, philadelphia", price: 3.00, category: "Onigiri" },
  { id: "oni-4", name: "Shake", description: "Salmone, avocado", price: 3.00, category: "Onigiri" },

  // Dolci (sorted alphabetically)
  { id: "dol-3", name: "Black biscuits", description: "Pan di Spagna al cacao vaniglia, crema al formaggio arricchita da scaglie di cioccolato di biscotti al cacao", price: 5.50, category: "Dolci" },
  { id: "dol-14", name: "Cocco e nocciola", price: 5.50, category: "Dolci" },
  { id: "dol-12", name: "Cocco ripieno", price: 5.50, category: "Dolci" },
  { id: "dol-13", name: "Coppa crema al pistacchio", price: 5.50, category: "Dolci" },
  { id: "dol-2", name: "Crema catalana in coccio", description: "Con zucchero caramellato", price: 6.00, category: "Dolci" },
  { id: "dol-6", name: "Delizia gelato rocher", price: 5.50, category: "Dolci" },
  { id: "dol-7", name: "Dorayaki al cioccolato", price: 5.00, category: "Dolci" },
  { id: "dol-8", name: "Flutè limoncello", price: 5.50, category: "Dolci" },
  { id: "dol-11", name: "Limone ripieno", price: 5.50, category: "Dolci" },
  { id: "dol-1", name: "Mochi 3 pezzi", description: "Dolce tipico giapponese a base di riso glutinoso ripieni di gelato al the verde, vaniglia, mango", price: 6.00, category: "Dolci" },
  { id: "dol-16", name: "Pan dan", description: "Gelato alla vaniglia", price: 5.00, category: "Dolci" },
  { id: "dol-19", name: "Pirata", description: "Gelato al cioccolato", price: 5.00, category: "Dolci" },
  { id: "dol-17", name: "Principessa", description: "Gelato alla fragola", price: 5.00, category: "Dolci" },
  { id: "dol-18", name: "Rabbit", description: "Gelato al fior di latte", price: 5.00, category: "Dolci" },
  { id: "dol-5", name: "Rocher cubano", description: "Gelato al cioccolato al rum di cuba, pan di Spagna, glassa al cioccolato", price: 5.50, category: "Dolci" },
  { id: "dol-9", name: "Tartufo bianco", price: 5.50, category: "Dolci" },
  { id: "dol-10", name: "Tartufo cocco e nocciola", price: 5.50, category: "Dolci" },
  { id: "dol-4", name: "Tartufo nero gianduia vegano", price: 5.50, category: "Dolci" },
  { id: "dol-15", name: "Torta al croccante", price: 5.50, category: "Dolci" },

  // Bevande (sorted alphabetically)
  { id: "bev-6", name: "Acqua frizzante 50cl", price: 1.50, category: "Bevande" },
  { id: "bev-5", name: "Acqua naturale 50cl", price: 1.50, category: "Bevande" },
  { id: "bev-1", name: "Coca-Cola 33cl in vetro", price: 2.50, category: "Bevande" },
  { id: "bev-3", name: "Coca-Cola Zero", price: 2.50, category: "Bevande" },
  { id: "bev-2", name: "Fanta", price: 2.50, category: "Bevande" },
  { id: "bev-4", name: "Tè al limone", price: 2.50, category: "Bevande" },
  { id: "bev-7", name: "Tè pesca", price: 2.50, category: "Bevande" },

  // Birre (sorted alphabetically)
  { id: "bir-4", name: "Birra Cinese Tsingtao", price: 4.00, category: "Birre" },
  { id: "bir-5", name: "Birra giapponese Asahi", price: 4.50, category: "Birre" },
  { id: "bir-3", name: "Heineken 66cl", price: 3.50, category: "Birre" },
  { id: "bir-2", name: "Peroni 33cl", price: 2.50, category: "Birre" },
  { id: "bir-1", name: "Peroni 66cl", price: 3.50, category: "Birre" }
];

export const FAQS: FAQItem[] = [
  {
    id: "faq-1",
    question: "Dove mangiare sushi all you can eat a Foggia?",
    answer: "Il nostro restaurante Xian Sushi si trova a Foggia, in Via Manfredonia 37. Proponiamo un'autentica formula sushi all you can eat a pranzo e a cena, con ingredienti freschissimi di alta qualità, preparazioni espresse e un ambiente premium ideale per trascorrere momenti in coppia, famiglia o con amici.",
  },
  {
    id: "faq-2",
    question: "Il ristorante ha un’area bimbi?",
    answer: "Sì, Xian Sushi dispone di un'esclusiva area bimbi attrezzata con gonfiabili e giochi sicuri, posizionata in uno spazio visibile ma insonorizzato. Questa soluzione è stata studiata per permettere ai genitori di gustare la propria cena sushi premium in assoluta serenità mentre i più piccoli si divertono in sicurezza.",
  },
  {
    id: "faq-3",
    question: "È possibile ordinare sushi da asporto?",
    answer: "Certamente! Dalla sezione 'Take Away & Delivery' del nostro sito web puoi scorrere le categorie, scegliere le tue specialità preferite, aggiungerle al carrello e completare la richiesta. Riceverai un codice ordine e invierai il riepilogo direttamente tramite WhatsApp al locale per un ritiro rapido.",
  },
  {
    id: "faq-4",
    question: "Fate sushi delivery a Foggia?",
    answer: "Sì, offriamo un servizio di consegna a domicilio (sushi delivery) a Foggia e nei comuni limitrofi. Al momento del checkout sul sito ti basterà selezionare 'Delivery', inserire il tuo indirizzo completo, recapito telefonico ed eventuali note. L'ordine verrà inviato via WhatsApp e ti verrà consegnato comodamente a casa.",
  },
  {
    id: "faq-5",
    question: "Come posso prenotare un tavolo?",
    answer: "Puoi prenotare in pochi secondi direttamente dal form di prenotazione presente nella Home Page del nostro sito. Basta inserire il tuo nome, telefono, data desiderata, numero di persone e fascia oraria preferita. Il sistema genererà un messaggio precompilato e ti collegherà a WhatsApp per confermare in tempo reale col locale.",
  },
  {
    id: "faq-6",
    question: "Quali sono i prezzi del menu all you can eat?",
    answer: "Offriamo diverse tariffe per venire incontro a tutte le esigenze. Il pranzo feriale (martedì-venerdì) costa €16,90, mentre la cena feriale è a €26,90. Nel weekend e nei giorni festivi il pranzo è a €18,90 e la cena è a €28,90. Le bevande, i dolci e il coperto sono esclusi da questa formula.",
  },
  {
    id: "faq-7",
    question: "Il ristorante è adatto alle famiglie?",
    answer: "Assolutamente sì. Xian Sushi è il ristorante di sushi ideale per famiglie a Foggia. Grazie ai nostri tavoli spaziosi, ad un'atmosfera elegante e accogliente, e soprattutto all'area bimbi con gonfiabili e giochi, garantiamo divertimento per i bambini e relax totale per i genitori.",
  },
  {
    id: "faq-8",
    question: "Como posso raggiungere il ristorante?",
    answer: "Il ristorante è situato a Foggia in Via Manfredonia 37, zona facilmente raggiungibile. Nella nostra pagina Contatti troverai una mappa interattiva integrata e un comodo pulsante per avviare la navigazione assistita con Google Maps direttamente dal tuo smartphone, anche se provieni da San Severo, Lucera, Manfredonia, Cerignola o altri comuni limitrofi.",
  },
];
